package com.entaingroup.nexon.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val primaryLight = Color(0xFF9E3E00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC64F00)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFF9B4507)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF4884A)
val onSecondaryContainerLight = Color(0xFF642800)
val tertiaryLight = Color(0xFF501FB6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF683FCF)
val onTertiaryContainerLight = Color(0xFFDED0FF)
val errorLight = Color(0xFFA51D11)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFC83727)
val onErrorContainerLight = Color(0xFFFFEBE8)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF251913)
val surfaceLight = Color(0xFFFDF8F7)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFEDE0DA)
val onSurfaceVariantLight = Color(0xFF4E4541)
val outlineLight = Color(0xFF7F7570)
val outlineVariantLight = Color(0xFFD1C4BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF32302F)
val inverseOnSurfaceLight = Color(0xFFF5F0EE)
val inversePrimaryLight = Color(0xFFFFB695)
val surfaceDimLight = Color(0xFFDED9D8)
val surfaceBrightLight = Color(0xFFFDF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F2F1)
val surfaceContainerLight = Color(0xFFF2EDEC)
val surfaceContainerHighLight = Color(0xFFECE7E6)
val surfaceContainerHighestLight = Color(0xFFE6E1E0)

// Dark theme
val primaryDark = Color(0xFFFFB695)
val onPrimaryDark = Color(0xFF571F00)
val primaryContainerDark = Color(0xFFED691E)
val onPrimaryContainerDark = Color(0xFF491900)
val secondaryDark = Color(0xFFFFB690)
val onSecondaryDark = Color(0xFF552100)
val secondaryContainerDark = Color(0xFFF4884A)
val onSecondaryContainerDark = Color(0xFF642800)
val tertiaryDark = Color(0xFFCEBDFF)
val onTertiaryDark = Color(0xFF390094)
val tertiaryContainerDark = Color(0xFF683FCF)
val onTertiaryContainerDark = Color(0xFFDED0FF)
val errorDark = Color(0xFFFFB4A8)
val onErrorDark = Color(0xFF690100)
val errorContainerDark = Color(0xFFC83727)
val onErrorContainerDark = Color(0xFFFFEBE8)
val backgroundDark = Color(0xFF1C110B)
val onBackgroundDark = Color(0xFFF6DED4)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE6E1E0)
val surfaceVariantDark = Color(0xFF4E4541)
val onSurfaceVariantDark = Color(0xFFD1C4BE)
val outlineDark = Color(0xFF9A8E89)
val outlineVariantDark = Color(0xFF4E4541)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E0)
val inverseOnSurfaceDark = Color(0xFF32302F)
val inversePrimaryDark = Color(0xFFA24000)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3938)
val surfaceContainerLowestDark = Color(0xFF0F0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF211F1F)
val surfaceContainerHighDark = Color(0xFF2B2A29)
val surfaceContainerHighestDark = Color(0xFF363434)
